[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D VERSION_STRING="2.0.0"
lib_deps =
    adafruit/Adafruit_VL53L0X@^1.2.4

[env:rover_v2_mpu6050_qmc5883l_tb6612]
build_flags =
    ${env.build_flags}
    -D USE_MPU6050
    -D USE_QMC5883L
    -D USE_TB6612

[env:rover_v2_bmi160_lis3mdl_tb6612]
build_flags =
    ${env.build_flags}
    -D USE_BMI160
    -D USE_LIS3MDL
    -D USE_TB6612

[env:rover_v2_mpu6050_hmc5883l_tb6612]
build_flags =
    ${env.build_flags}
    -D USE_MPU6050
    -D USE_HMC5883L
    -D USE_TB6612

[env:firmware_sensor_calibration]
build_flags =
    ${env.build_flags}
    -D MODE_CALIBRATION
