[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D VERSION_STRING="3.0.0"
lib_deps =
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit_VL53L0X @ ^1.2.4
    fastled/FastLED@^3.6.0
    madhephaestus/ESP32Servo@^3.0.5
